<?php
// ------------- AUTOGENERATED FILE ---------------- //
if(!defined('INCLUDE_CHECK')) die('You are not allowed to execute this file directly');

// ------------- USER STUFF ---------------- //
/* Password for CA private key (used to generate client certs) */
$CApass = 'asd123';
/* OpenSSL config file location */
$SSLconf = '/var/www/ssl/myprofileCA/openssl.cnf';

/* IDP address */
$idp = 'https://auth.my-profile.eu/auth/index.php?authreqissuer=';

/* Database config */
$db_database   = 'myprofile';
$db_host       = 'localhost';
$db_user       = 'myprofile';
$db_pass       = 'ph34rb07';

// Establish db connection
mysql_connect($db_host,$db_user,$db_pass) or die('Unable to establish a DB connection');
mysql_select_db($db_database);
mysql_query("SET names UTF8");
?>