<?php
// ------------- AUTOGENERATED FILE ---------------- //
if(!defined('INCLUDE_CHECK')) die('You are not allowed to execute this file directly');

// ------------- USER STUFF ---------------- //
/* Password for CA private key (used to generate client certs) */
define ('CA_PASS', 'asd123');
/* OpenSSL config file location */
define ('SSL_CONF', '/var/www/ssl/myprofileCA/openssl.cnf');

/* IDP address */
define ('IDP', 'https://auth.my-profile.eu/auth/?authreqissuer=');

/* SPARQL endpoint */
define ('SPARQL_ENDPOINT', 'http://localhost:8890/sparql');

/* Database config */
define ('DB_DATABASE', 'myprofile');
define ('DB_HOST', 'localhost');
define ('DB_USER', 'myprofile');
define ('DB_PASS', 'ph34rb07');

/* SMTP config */
define ('SMTP_AUTHENTICATION', 1);
define ('SMTP_SERVER', 'mail.gandi.net');
define ('SMTP_USERNAME', 'notifications@my-profile.eu');
define ('SMTP_PASSWORD', 'shitfuckpass');

// Establish db connection
mysql_connect(DB_HOST, DB_USER, DB_PASS) or die('Unable to establish a database connection');
mysql_select_db(DB_DATABASE);
mysql_query("SET names UTF8");
?>
