<?php
//-----------------------------------------------------------------------------------------------------------------------------------
//
// Filename   : Authentication_X509CertRepo.php
// Date       : 26th Mar 2010
//
// Copyright 2008-2010 foaf.me
//
// This program is free software: you can redistribute it and/or modify
// it under the terms of the GNU Affero General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
//
// This program is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
// GNU Affero General Public License for more details.
//
// You should have received a copy of the GNU Affero General Public License
// along with this program. If not, see <http://www.gnu.org/licenses/>.
//
// "Everything should be made as simple as possible, but no simpler."
// -- Albert Einstein
//
//-----------------------------------------------------------------------------------------------------------------------------------


/**
 * An X509Certificate repository
 *
 * @author László Török
 */
class Authentication_X509CertRepo
{
    const DEFAULT_IDP = 'foafssl.org';
    
    private $IDPCertificates = array ( self::DEFAULT_IDP =>
"-----BEGIN CERTIFICATE-----
MIIHHDCCBgSgAwIBAgIDA/qDMA0GCSqGSIb3DQEBBQUAMIGMMQswCQYDVQQGEwJJ
TDEWMBQGA1UEChMNU3RhcnRDb20gTHRkLjErMCkGA1UECxMiU2VjdXJlIERpZ2l0
YWwgQ2VydGlmaWNhdGUgU2lnbmluZzE4MDYGA1UEAxMvU3RhcnRDb20gQ2xhc3Mg
MSBQcmltYXJ5IEludGVybWVkaWF0ZSBTZXJ2ZXIgQ0EwHhcNMTEwODA5MTMwMjQy
WhcNMTIwODA5MDgxOTM1WjBkMSAwHgYDVQQNExc0ODE2NDQtbjU3MHFFcTk3Zkky
RDMzOTEYMBYGA1UEAxMPd3d3LmZvYWZzc2wub3JnMSYwJAYJKoZIhvcNAQkBFhdo
ZW5yeS5zdG9yeUBiYmxmaXNoLm5ldDCCASIwDQYJKoZIhvcNAQEBBQADggEPADCC
AQoCggEBAIRW6IsEuR87EAAHqxjo/GZOqrxH9kFWq5ZvnNX8Xen9zqEPXs4m9S41
4rcPs9sXCxvJc2k5ijlNI8Oymaeli1uoKoQFo9gUNS5JfUe2gFKQN8qZOdoIpPLv
+SYlqU7dRFffQz+Vzc80P0FY5LwZY62PtWXjPl7Ssxn2yu3loefN8Z9wBOpmqa13
ywKNwY1FiTkHtFRxmIKwVTnEUK0kOt+P3/o5NtrZmGUc3U0/2QmnXi3eza8iHiWx
LtFtdOSWLyqHWsEjN/847eH1xSD8gc/Lxx5h0XdrMg1qlMuOmFUH6gn1AXV5B271
UAbQH70RlIWGxUJvdump+s/bkROSwmkCAwEAAaOCA6wwggOoMAkGA1UdEwQCMAAw
CwYDVR0PBAQDAgOoMBMGA1UdJQQMMAoGCCsGAQUFBwMBMB0GA1UdDgQWBBRYkyo8
Dq4Za9xzfoxc9f2vANZNFjAfBgNVHSMEGDAWgBTrQjTQmLCrn/Qbawj3zGQu7w4s
RTAnBgNVHREEIDAegg93d3cuZm9hZnNzbC5vcmeCC2ZvYWZzc2wub3JnMIICIQYD
VR0gBIICGDCCAhQwggIQBgsrBgEEAYG1NwECAjCCAf8wLgYIKwYBBQUHAgEWImh0
dHA6Ly93d3cuc3RhcnRzc2wuY29tL3BvbGljeS5wZGYwNAYIKwYBBQUHAgEWKGh0
dHA6Ly93d3cuc3RhcnRzc2wuY29tL2ludGVybWVkaWF0ZS5wZGYwgfcGCCsGAQUF
BwICMIHqMCcWIFN0YXJ0Q29tIENlcnRpZmljYXRpb24gQXV0aG9yaXR5MAMCAQEa
gb5UaGlzIGNlcnRpZmljYXRlIHdhcyBpc3N1ZWQgYWNjb3JkaW5nIHRvIHRoZSBD
bGFzcyAxIFZhbGlkYXRpb24gcmVxdWlyZW1lbnRzIG9mIHRoZSBTdGFydENvbSBD
QSBwb2xpY3ksIHJlbGlhbmNlIG9ubHkgZm9yIHRoZSBpbnRlbmRlZCBwdXJwb3Nl
IGluIGNvbXBsaWFuY2Ugb2YgdGhlIHJlbHlpbmcgcGFydHkgb2JsaWdhdGlvbnMu
MIGcBggrBgEFBQcCAjCBjzAnFiBTdGFydENvbSBDZXJ0aWZpY2F0aW9uIEF1dGhv
cml0eTADAgECGmRMaWFiaWxpdHkgYW5kIHdhcnJhbnRpZXMgYXJlIGxpbWl0ZWQh
IFNlZSBzZWN0aW9uICJMZWdhbCBhbmQgTGltaXRhdGlvbnMiIG9mIHRoZSBTdGFy
dENvbSBDQSBwb2xpY3kuMDUGA1UdHwQuMCwwKqAooCaGJGh0dHA6Ly9jcmwuc3Rh
cnRzc2wuY29tL2NydDEtY3JsLmNybDCBjgYIKwYBBQUHAQEEgYEwfzA5BggrBgEF
BQcwAYYtaHR0cDovL29jc3Auc3RhcnRzc2wuY29tL3N1Yi9jbGFzczEvc2VydmVy
L2NhMEIGCCsGAQUFBzAChjZodHRwOi8vYWlhLnN0YXJ0c3NsLmNvbS9jZXJ0cy9z
dWIuY2xhc3MxLnNlcnZlci5jYS5jcnQwIwYDVR0SBBwwGoYYaHR0cDovL3d3dy5z
dGFydHNzbC5jb20vMA0GCSqGSIb3DQEBBQUAA4IBAQCfJMOvI2yOWtZ0Bhc38KYu
9p8qkKah5gssWLNFIsYWw7khPUUSvKrxAPJKO2pAoFeP8ex2vsnuBzgmnhMsw++O
8wwbD6BzGBD2hw2AFwWzz2Dhxo6k3gEsxqTHuFyGrgo54AQEiBCaFmGy7Qs5Hv7w
yonB8Xt0GtShQiLe3XbXpxQsc0NDpk+odo2vE9eq5Qr/QFpZT8GIw2gYQmP2Kbkm
neH+FRVPd0LwlwZjFowyBYe5v2bpU+5AH3QQe2pYK+TSK4qyBsBzETY6QToDJXFC
zZHMSzGH8LsI+nnoJfaI1FuhYACaqE420PNUgN3h4MgliOKOiWwsgDf2R51gnfNe
-----END CERTIFICATE-----", 
"lor-8175.int-evry.fr" =>
"-----BEGIN CERTIFICATE-----
MIIDGjCCAoOgAwIBAgIJAPWKstF2BhLjMA0GCSqGSIb3DQEBBQUAMFYxCzAJBgNV
BAYTAkZSMRAwDgYDVQQIEwdFc3Nvbm5lMRMwEQYDVQQKEwpUU1AgLSBBMTA2MQww
CgYDVQQLEwNMT1IxEjAQBgNVBAMTCUFuZHJlaSBTLjAeFw0xMTAzMjgxMzQ3MTha
Fw0xMjAzMjcxMzQ3MThaMIGLMQswCQYDVQQGEwJGUjEQMA4GA1UECBMHRXNzb25u
ZTEZMBcGA1UEChMQVEVMRUNPTSBTdWRQYXJpczERMA8GA1UECxMITE9SIEExNjAx
HTAbBgNVBAMTFGxvci04MTc1LmludC1ldnJ5LmZyMR0wGwYJKoZIhvcNAQkBFg5h
bmRyZWlAZmNucy5ldTCBnzANBgkqhkiG9w0BAQEFAAOBjQAwgYkCgYEAp108O2xW
Ai9nTq/AF/fJn1fhzgBK3ui23T3L2iMdru/L7ph7tPDOJfJliZpGKuOMZPHqxMgK
2UciaKRztGHV8bOYSuH6LnK+hRb1h6cR/CBPUXJasfsu8mYn5e340trb4mTnd/vj
jR+YvxbHCuczViZQ6Zz1HmQOA6YRhe7L0BsCAwEAAaOBuTCBtjAdBgNVHQ4EFgQU
N2/oXkd0KdnMxYs7/vXvRjxfetQwgYYGA1UdIwR/MH2AFM9JsU1M3F/4pngR4CWe
A+4QYbYsoVqkWDBWMQswCQYDVQQGEwJGUjEQMA4GA1UECBMHRXNzb25uZTETMBEG
A1UEChMKVFNQIC0gQTEwNjEMMAoGA1UECxMDTE9SMRIwEAYDVQQDEwlBbmRyZWkg
Uy6CCQD1irLRdgYSqTAMBgNVHRMEBTADAQH/MA0GCSqGSIb3DQEBBQUAA4GBAIbK
rJTFu1lwASE6VsFOoI0NMh57a9RmdiJNui3qL6AU8bm4LJ7/ULe+DH/Mocd2cvg1
SVXse9akR1t2OxR8Zji/wFEo3LMFPpiCBwGz8Czw4niJHJoyKYW1uhzbIflIcay7
b4IrgJFOQnvW+AHMA0ETGS9E+DGoIl999F0bruMS
-----END CERTIFICATE-----",
"auth.fcns.eu" =>
"-----BEGIN CERTIFICATE-----
MIIElDCCA3ygAwIBAgILAQAAAAABLyznhtwwDQYJKoZIhvcNAQEFBQAwNjERMA8G
A1UECxMIQWxwaGEgQ0ExDjAMBgNVBAoTBUFscGhhMREwDwYDVQQDEwhBbHBoYSBD
QTAeFw0xMTA0MDYyMTMxMzNaFw0xMjA0MDYyMTMxMzBaMFgxCzAJBgNVBAYTAkZS
MSEwHwYDVQQLExhEb21haW4gQ29udHJvbCBWYWxpZGF0ZWQxEjAQBgNVBAoMCSou
ZmNucy5ldTESMBAGA1UEAwwJKi5mY25zLmV1MIIBIjANBgkqhkiG9w0BAQEFAAOC
AQ8AMIIBCgKCAQEAyfLj5x7XR+v07NgOCtOcKJgMkq7p1rEvSQ9jfTFYDcL454wv
4QFS6OLnkH6KpV61npj0XYznYycgmNvWw9cDRdhN+fLW0VKqSRYqNAkvSc1JkmW9
JisldX33iTiyhVoEDfviu9pMBImalZ1y14A4LPHAkV5rZy/fRk7F/gMo29JuLSmP
ngu4ze/+oHHp1+EiIlhMi8exisQvVhhc9n2CRWL5eYmG9Qr90C1nJnMygDKraTFj
3CxStk0HN5NhNYKe1kNFElny9hLxlpL8D0UlVYhfC0gRHc6mTRB3NEfSmkQCWJCR
1iV9ZrMFD5fO27w5AkMIN4AULUMNxLed3KmC1QIDAQABo4IBfzCCAXswHwYDVR0j
BBgwFoAUCin6ra9N/f1dfXYmh6uqWqp0IhUwTQYIKwYBBQUHAQEEQTA/MD0GCCsG
AQUFBzAChjFodHRwOi8vc2VjdXJlLmFscGhhc3NsLmNvbS9jYWNlcnQvQWxwaGFT
U0xkdjEuY3J0MDIGA1UdHwQrMCkwJ6AloCOGIWh0dHA6Ly9jcmwuYWxwaGFzc2wu
Y29tL0FscGhhLmNybDAdBgNVHQ4EFgQU/zLAtIZbTa0IkyiX7Ca95AFp3iowCQYD
VR0TBAIwADAOBgNVHQ8BAf8EBAMCBaAwHQYDVR0lBBYwFAYIKwYBBQUHAwEGCCsG
AQUFBwMCMEoGA1UdIARDMEEwPwYKKwYBBAGgMgEKCjAxMC8GCCsGAQUFBwIBFiNo
dHRwOi8vd3d3LmFscGhhc3NsLmNvbS9yZXBvc2l0b3J5LzARBglghkgBhvhCAQEE
BAMCBsAwHQYDVR0RBBYwFIIJKi5mY25zLmV1ggdmY25zLmV1MA0GCSqGSIb3DQEB
BQUAA4IBAQCYins7oSJi8ULUuo+eoAqhNPzPPweTqfwCW1dshvkyE7CjZnWmzDXR
XPgFhpwfXCiZ5Nh76mSuQ4sxZvoEJhh3Q3wXOhRkBNrDlUWoWGftfruwji8RgGkJ
piNGsdrBkjFucGgwPE79dya6wMgWmw2XvRnft/JTs2e3Epvm99B0trszb9AYk6sx
rkCGu+VOfWZIu0uu63rrWWMVLQi5OAFBbuczOLYXE/76PpMYbiKORGr8gXzmZ/zq
y24vK4vwFIrWXgldC6FkiI2RBL5to4bWlD/bPjOwpFMfiOOqCALs5zBr/ijIAib3
sbT0swwb2fUto/0Nl7hw9oyQpckoilKX
-----END CERTIFICATE-----",
"auth.my-profile.eu" => 
"-----BEGIN CERTIFICATE-----
MIIHKzCCBhOgAwIBAgIDBerZMA0GCSqGSIb3DQEBBQUAMIGMMQswCQYDVQQGEwJJ
TDEWMBQGA1UEChMNU3RhcnRDb20gTHRkLjErMCkGA1UECxMiU2VjdXJlIERpZ2l0
YWwgQ2VydGlmaWNhdGUgU2lnbmluZzE4MDYGA1UEAxMvU3RhcnRDb20gQ2xhc3Mg
MSBQcmltYXJ5IEludGVybWVkaWF0ZSBTZXJ2ZXIgQ0EwHhcNMTIwNDA0MTA0NTEw
WhcNMTMwNDA0MTg1MjI3WjBuMRkwFwYDVQQNExBoWTdENnQ3M1A5Y1B2ckF6MQsw
CQYDVQQGEwJGUjEbMBkGA1UEAxMSYXV0aC5teS1wcm9maWxlLmV1MScwJQYJKoZI
hvcNAQkBFhhwb3N0bWFzdGVyQG15LXByb2ZpbGUuZXUwggEiMA0GCSqGSIb3DQEB
AQUAA4IBDwAwggEKAoIBAQC9Ix5SIxwgZjGvx63VXYhFU2+A94FXEO7qr1Ri1ZdZ
WUjItBUNvK6JzdFA1oAPYtGMDs/Uev99Ibj4FfUT3R2GYI2WWv1nGZk6zXFN51Z3
2JAXh1XgX1IW47mhVfzR2yy/i31yPn0oOEhyA3R3dYPs3K6HTd1Eng2rtzbYieVK
zamTkVQmyMG2WFmJBbJ5QoCRkGHR5ZnkJ/4jhZF41GyTTW71dcwOb3ITi9GDsSHv
D5jfUTZy5PXN/91H48SdrVVj6KEziD4h7FnPHpgzpsKJt1wehc83EWR89IEeY/dC
62sNz0s1sMg1BNhoqKesdCSUhjEURGyqGUaF7Ge+0baJAgMBAAGjggOxMIIDrTAJ
BgNVHRMEAjAAMAsGA1UdDwQEAwIDqDATBgNVHSUEDDAKBggrBgEFBQcDATAdBgNV
HQ4EFgQUMM0hTiEKfr0/Lp85d7KgQlBfNgcwHwYDVR0jBBgwFoAU60I00Jiwq5/0
G2sI98xkLu8OLEUwLAYDVR0RBCUwI4ISYXV0aC5teS1wcm9maWxlLmV1gg1teS1w
cm9maWxlLmV1MIICIQYDVR0gBIICGDCCAhQwggIQBgsrBgEEAYG1NwECAjCCAf8w
LgYIKwYBBQUHAgEWImh0dHA6Ly93d3cuc3RhcnRzc2wuY29tL3BvbGljeS5wZGYw
NAYIKwYBBQUHAgEWKGh0dHA6Ly93d3cuc3RhcnRzc2wuY29tL2ludGVybWVkaWF0
ZS5wZGYwgfcGCCsGAQUFBwICMIHqMCcWIFN0YXJ0Q29tIENlcnRpZmljYXRpb24g
QXV0aG9yaXR5MAMCAQEagb5UaGlzIGNlcnRpZmljYXRlIHdhcyBpc3N1ZWQgYWNj
b3JkaW5nIHRvIHRoZSBDbGFzcyAxIFZhbGlkYXRpb24gcmVxdWlyZW1lbnRzIG9m
IHRoZSBTdGFydENvbSBDQSBwb2xpY3ksIHJlbGlhbmNlIG9ubHkgZm9yIHRoZSBp
bnRlbmRlZCBwdXJwb3NlIGluIGNvbXBsaWFuY2Ugb2YgdGhlIHJlbHlpbmcgcGFy
dHkgb2JsaWdhdGlvbnMuMIGcBggrBgEFBQcCAjCBjzAnFiBTdGFydENvbSBDZXJ0
aWZpY2F0aW9uIEF1dGhvcml0eTADAgECGmRMaWFiaWxpdHkgYW5kIHdhcnJhbnRp
ZXMgYXJlIGxpbWl0ZWQhIFNlZSBzZWN0aW9uICJMZWdhbCBhbmQgTGltaXRhdGlv
bnMiIG9mIHRoZSBTdGFydENvbSBDQSBwb2xpY3kuMDUGA1UdHwQuMCwwKqAooCaG
JGh0dHA6Ly9jcmwuc3RhcnRzc2wuY29tL2NydDEtY3JsLmNybDCBjgYIKwYBBQUH
AQEEgYEwfzA5BggrBgEFBQcwAYYtaHR0cDovL29jc3Auc3RhcnRzc2wuY29tL3N1
Yi9jbGFzczEvc2VydmVyL2NhMEIGCCsGAQUFBzAChjZodHRwOi8vYWlhLnN0YXJ0
c3NsLmNvbS9jZXJ0cy9zdWIuY2xhc3MxLnNlcnZlci5jYS5jcnQwIwYDVR0SBBww
GoYYaHR0cDovL3d3dy5zdGFydHNzbC5jb20vMA0GCSqGSIb3DQEBBQUAA4IBAQBp
JFAAxZ2gzThBLAGITaUqXBLMgauQQkFjK6AwmPXu3XxDpxAsXTM6ce0DpwOjDWXQ
CCvF8pydSUKBIwuGN8BcQaC5qnyHamc62YO5Q+VkHbRcLyCB/zqjsOO2+G75AZf9
Z9PIzHUFTxIO2rWu76K6IT8vIpjiIwfF5r5irPOzjbWTFTCQwbhBCF7XdMPlma6d
UFGtn+/N7Hg5F/TPHdI7z/oJIkTP79h73+H9Nv6OD7DKIMWZBfvwR9vNIxvaLOMW
0uxmn9nSfUiAHli5nhvI6gAk1JJf31sOkWmd66KIQzC4pR+GRjPzdmbZpXCjqbjq
rsXEfOCMHw9T3c5vV5qy
-----END CERTIFICATE-----");

    public function  __construct(array $IDPCertificates = array())
    {
        $this->IDPCertificates =
                array_merge($this->IDPCertificates, $IDPCertificates);
    }

    /**
     * Get the Identity Provider's certificate
     * @param string $IPDDomainName Identity Provider's domain name
     *        (e.g. foafssl.org)
     * @return object requiested x509 certificate content
     *         (or the default IDP's certificate, if the requested is not found)
     */
    public function getIdpCertificate($IDPDomainName)
    {
       return isset($this->IDPCertificates[$IDPDomainName]) ?
               $this->IDPCertificates[$IDPDomainName]
              : $this->IDPCertificates[self::DEFAULT_IDP];
    }
}
?>
